### ISSUE TITLE
Beware, default passwords in configuration files

### ISSUE THREAD

**Issue by cozybear-dev** [reverse-hash/bitcoin-full-node-with-docker#3]
In the instructions and readme, are no comments regarding the configured credentials. It's advised to let new users change these with their own passwords. I'm receiving my hardware in a few weeks, will update this issue with a PR to easily update this for other new users.

https://github.com/reverse-hash/bitcoin-full-node-with-docker/blob/82bf7d41e05c3ace67bce806ec7c12e37f9dc59c/volumes/bitcoind/bitcoin.conf#L36

https://github.com/reverse-hash/bitcoin-full-node-with-docker/blob/82bf7d41e05c3ace67bce806ec7c12e37f9dc59c/volumes/btc-rpc-explorer/btc-rpc-explorer.env#L37

https://github.com/reverse-hash/bitcoin-full-node-with-docker/blob/82bf7d41e05c3ace67bce806ec7c12e37f9dc59c/volumes/electrs/electrs.conf#L9

**Comment by reverse-hash** [comment]
Good point! I will be happy to add your suggestions.

**Comment by reverse-hash** [comment]
Already integrated.
